In [19]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
# Question 10
    # First calculated the total_revenue by joining Facilities and Bookings; used CASE WHEN. Then used it as a sub-query  
    query1 = """

SELECT s.name, SUM(s.revenue) AS total_revenue
FROM (SELECT name, 
		CASE WHEN b.memid = 0 THEN (b.slots * f.guestcost)
			ELSE (b.slots * f.membercost) END AS revenue
		FROM Bookings AS b
		LEFT JOIN Facilities AS f
			ON f.facid = b.facid) AS s
GROUP BY s.name
HAVING total_revenue > 1000
ORDER BY total_revenue DESC"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Massage Room 1', 50351.600000000275)
('Massage Room 2', 14454.599999999995)
('Tennis Court 2', 14310)
('Tennis Court 1', 13860)
('Squash Court', 13468.0)
('Badminton Court', 1906.5)

In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
# Question 11
    query1 = """

SELECT m1.firstname, m1.surname, m2.firstname, m2.surname
FROM Members AS m1
LEFT JOIN Members AS m2
ON m2.memid = m1.recommendedby
WHERE m2.memid != 0 AND m1.recommendedby IS NOT NULL
ORDER BY m1.firstname, m1.surname"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Anna', 'Mackenzie', 'Darren', 'Smith')
('Anne', 'Baker', 'Ponder', 'Stibbons')
('Charles', 'Owen', 'Darren', 'Smith')
('David', 'Jones', 'Janice', 'Joplette')
('David', 'Pinker', 'Jemima', 'Farrell')
('Douglas', 'Jones', 'David', 'Jones')
('Erica', 'Crumpet', 'Tracy', 'Smith')
('Florence', 'Bader', 'Ponder', 'Stibbons')
('Gerald', 'Butters', 'Darren', 'Smith')
('Henrietta', 'Rumney', 'Matthew', 'Genting')
('Henry', 'Worthington-Smyth', 'Tracy', 'Smith')
('Jack', 'Smith', 'Darren', 'Smith')
('Janice', 'Joplette', 'Darren', 'Smith')
('Joan', 'Coplin', 'Timothy', 'Baker')
('John', 'Hunt', 'Millicent', 'Purview')
('Matthew', 'Genting', 'Gerald', 'Butters')
('Millicent', 'Purview', 'Tracy', 'Smith')
('Nancy', 'Dare', 'Janice', 'Joplette')
('Ponder', 'Stibbons', 'Burton', 'Tracy')
('Ramnaresh', 'Sarwin', 'Florence', 'Bader')
('Tim', 'Boothe', 'Tim', 'Rownam')
('Timothy', 'Baker', 'Jemima', 'Farrell')

In [2]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
# Question 12
    query1 = """SELECT m.firstname, m.surname, SUM(b.slots) AS total_slots
FROM Bookings AS b
LEFT JOIN Members AS m
ON b.memid = m.memid
WHERE b.memid != 0
GROUP BY b.memid
ORDER BY total_slots DESC

"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Darren', 'Smith', 685)
('Tim', 'Rownam', 660)
('Tim', 'Boothe', 440)
('Tracy', 'Smith', 435)
('Gerald', 'Butters', 409)
('Burton', 'Tracy', 366)
('Charles', 'Owen', 345)
('Janice', 'Joplette', 326)
('David', 'Jones', 305)
('Anne', 'Baker', 296)
('Timothy', 'Baker', 290)
('Nancy', 'Dare', 267)
('Ponder', 'Stibbons', 249)
('Florence', 'Bader', 237)
('Anna', 'Mackenzie', 231)
('Jack', 'Smith', 219)
('Jemima', 'Farrell', 180)
('David', 'Pinker', 159)
('Ramnaresh', 'Sarwin', 153)
('Matthew', 'Genting', 131)
('Joan', 'Coplin', 106)
('Henry', 'Worthington-Smyth', 60)
('David', 'Farrell', 50)
('John', 'Hunt', 40)
('Henrietta', 'Rumney', 38)
('Douglas', 'Jones', 37)
('Millicent', 'Purview', 32)
('Hyacinth', 'Tupperware', 28)
('Erica', 'Crumpet', 17)

In [7]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
# Question 13 
    query1 = """ SELECT strftime('%m',starttime) AS month, SUM(slots) AS total_slots
        FROM Bookings
        WHERE memid != 0
        GROUP BY month
        ORDER BY total_slots DESC"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('09', 3199)
('08', 2531)
('07', 1061)